let accion_def_tests = Array(
   Array("accion", "id_accion", "input", 1, "cumple tamaño numerico minimo id_accion en ADD", "min_size", "ADD", "id_accion_min_size_ko", "Mínimo 1"),
   Array("accion", "id_accion", "input", 2, "cumple tamaño numerico minimo id_accion en EDIT", "min_size", "EDIT", "id_accion_min_size_ko", "Mínimo 1"),
   Array("accion", "id_accion", "input", 3, "cumple tamaño numerico maximo id_accion en ADD", "max_size", "ADD", "id_accion_max_size_ko", "Máximo 11"),
   Array("accion", "id_accion", "input", 4, "cumple tamaño numerico maximo id_accion en EDIT", "max_size", "EDIT", "id_accion_max_size_ko", "Máximo 11"),
   Array("accion", "id_accion", "input", 5, "cumple tamaño numerico maximo id_accion en SEARCH", "max_size", "SEARCH", "id_accion_max_size_ko", "Máximo 11"),
   Array("accion", "id_accion", "input", 6, "es correcto id_accion en ADD", "valid", "ADD", true, "ID acción correcto"),
   Array("accion", "id_accion", "input", 7, "es correcto id_accion en EDIT", "valid", "EDIT", true, "ID acción correcto"),
   Array("accion", "id_accion", "input", 8, "es correcto id_accion en SEARCH", "valid", "SEARCH", true, "ID acción correcto"),
   Array("accion", "nombre_accion", "input", 9, "cumple tamaño minimo nombre_accion en ADD", "min_size", "ADD", "nombre_accion_min_size_ko", "Nombre muy corto (min 5)"),
   Array("accion", "nombre_accion", "input", 10, "cumple tamaño minimo nombre_accion en EDIT", "min_size", "EDIT", "nombre_accion_min_size_ko", "Nombre muy corto (min 5)"),
   Array("accion", "nombre_accion", "input", 11, "cumple tamaño maximo nombre_accion en ADD", "max_size", "ADD", "nombre_accion_max_size_ko", "Nombre muy largo (max 48)"),
   Array("accion", "nombre_accion", "input", 12, "cumple tamaño maximo nombre_accion en EDIT", "max_size", "EDIT", "nombre_accion_max_size_ko", "Nombre muy largo (max 48)"),
   Array("accion", "nombre_accion", "input", 13, "cumple tamaño maximo nombre_accion en SEARCH", "max_size", "SEARCH", "nombre_accion_max_size_ko", "Nombre muy largo (max 48)"),
   Array("accion", "nombre_accion", "input", 14, "cumple formato alfabetico con ñ en ADD", "format", "ADD", "nombre_accion_format_ko", "Formato inválido"),
   Array("accion", "nombre_accion", "input", 15, "cumple formato alfabetico con ñ en EDIT", "format", "EDIT", "nombre_accion_format_ko", "Formato inválido"),
   Array("accion", "nombre_accion", "input", 16, "cumple formato alfabetico con ñ en SEARCH", "format", "SEARCH", "nombre_accion_format_ko", "Formato inválido"),
   Array("accion", "nombre_accion", "input", 17, "es correcto nombre_accion en ADD", "valid", "ADD", true, "Acción correcta"),
   Array("accion", "nombre_accion", "input", 18, "es correcto nombre_accion en EDIT", "valid", "EDIT", true, "Acción correcta"),
   Array("accion", "nombre_accion", "input", 19, "es correcto nombre_accion en SEARCH", "valid", "SEARCH", true, "Acción correcta"),
   Array("accion", "descrip_accion", "input", 20, "cumple tamaño minimo descrip_accion en ADD", "min_size", "ADD", "descrip_accion_min_size_ko", "Descripción muy corta (min 5)"),
   Array("accion", "descrip_accion", "input", 21, "cumple tamaño minimo descrip_accion en EDIT", "min_size", "EDIT", "descrip_accion_min_size_ko", "Descripción muy corta (min 5)"),
   Array("accion", "descrip_accion", "input", 22, "cumple tamaño maximo descrip_accion en ADD", "max_size", "ADD", "descrip_accion_max_size_ko", "Descripción muy larga (max 200)"),
   Array("accion", "descrip_accion", "input", 23, "cumple tamaño maximo descrip_accion en EDIT", "max_size", "EDIT", "descrip_accion_max_size_ko", "Descripción muy larga (max 200)"),
   Array("accion", "descrip_accion", "input", 24, "cumple tamaño maximo descrip_accion en SEARCH", "max_size", "SEARCH", "descrip_accion_max_size_ko", "Descripción muy larga (max 200)"),
   Array("accion", "descrip_accion", "input", 25, "cumple formato alfabetico con ñ, espacio y puntuacion en ADD", "format", "ADD", "descrip_accion_format_ko", "Formato inválido"),
   Array("accion", "descrip_accion", "input", 26, "cumple formato alfabetico con ñ, espacio y puntuacion en EDIT", "format", "EDIT", "descrip_accion_format_ko", "Formato inválido"),
   Array("accion", "descrip_accion", "input", 27, "cumple formato alfabetico con ñ, espacio y puntuacion en SEARCH", "format", "SEARCH", "descrip_accion_format_ko", "Formato inválido"),
   Array("accion", "descrip_accion", "input", 28, "es correcto descrip_accion en ADD", "valid", "ADD", true, "Descripción correcta"),
   Array("accion", "descrip_accion", "input", 29, "es correcto descrip_accion en EDIT", "valid", "EDIT", true, "Descripción correcta"),
   Array("accion", "descrip_accion", "input", 30, "es correcto descrip_accion en SEARCH", "valid", "SEARCH", true, "Descripción correcta")
);

let accion_pruebas = Array(
   Array("accion", "id_accion", 1, 1, "ADD", {"id_accion":0}, "id_accion_min_size_ko"),
   Array("accion", "id_accion", 1, 2, "ADD", {"id_accion":1}, true),
   Array("accion", "id_accion", 2, 3, "EDIT", {"id_accion":0}, "id_accion_min_size_ko"),
   Array("accion", "id_accion", 2, 4, "EDIT", {"id_accion":1}, true),
   Array("accion", "id_accion", 3, 5, "ADD", {"id_accion":12}, "id_accion_max_size_ko"),
   Array("accion", "id_accion", 3, 6, "ADD", {"id_accion":11}, true),
   Array("accion", "id_accion", 4, 7, "EDIT", {"id_accion":12}, "id_accion_max_size_ko"),
   Array("accion", "id_accion", 4, 8, "EDIT", {"id_accion":11}, true),
   Array("accion", "id_accion", 5, 9, "SEARCH", {"id_accion":12}, "id_accion_max_size_ko"),
   Array("accion", "id_accion", 5, 10, "SEARCH", {"id_accion":11}, true),
   Array("accion", "id_accion", 6, 11, "ADD", {"id_accion":3}, true),
   Array("accion", "id_accion", 7, 12, "EDIT", {"id_accion":3}, true),
   Array("accion", "id_accion", 8, 13, "SEARCH", {"id_accion":3}, true),
   Array("accion", "nombre_accion", 9, 14, "ADD", {"nombre_accion":"act"}, "nombre_accion_min_size_ko"),
   Array("accion", "nombre_accion", 9, 15, "ADD", {"nombre_accion":"Añadir"}, true),
   Array("accion", "nombre_accion", 10, 16, "EDIT", {"nombre_accion":"act"}, "nombre_accion_min_size_ko"),
   Array("accion", "nombre_accion", 10, 17, "EDIT", {"nombre_accion":"Añadir"}, true),
   Array("accion", "nombre_accion", 11, 18, "ADD", {"nombre_accion":"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"}, "nombre_accion_max_size_ko"),
   Array("accion", "nombre_accion", 11, 19, "ADD", {"nombre_accion":"Modificación"}, true),
   Array("accion", "nombre_accion", 12, 20, "EDIT", {"nombre_accion":"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"}, "nombre_accion_max_size_ko"),
   Array("accion", "nombre_accion", 12, 21, "EDIT", {"nombre_accion":"Modificación"}, true),
   Array("accion", "nombre_accion", 13, 22, "SEARCH", {"nombre_accion":"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"}, "nombre_accion_max_size_ko"),
   Array("accion", "nombre_accion", 13, 23, "SEARCH", {"nombre_accion":"Modificación"}, true),
   Array("accion", "nombre_accion", 14, 24, "ADD", {"nombre_accion":"Añadir123"}, "nombre_accion_format_ko"),
   Array("accion", "nombre_accion", 14, 25, "ADD", {"nombre_accion":"Diseñar"}, true),
   Array("accion", "nombre_accion", 15, 26, "EDIT", {"nombre_accion":"Añadir123"}, "nombre_accion_format_ko"),
   Array("accion", "nombre_accion", 15, 27, "EDIT", {"nombre_accion":"Diseñar"}, true),
   Array("accion", "nombre_accion", 16, 28, "SEARCH", {"nombre_accion":"Añadir123"}, "nombre_accion_format_ko"),
   Array("accion", "nombre_accion", 16, 29, "SEARCH", {"nombre_accion":"Diseñar"}, true),
   Array("accion", "nombre_accion", 17, 30, "ADD", {"nombre_accion":"Consultar"}, true),
   Array("accion", "nombre_accion", 18, 31, "EDIT", {"nombre_accion":"Consultar"}, true),
   Array("accion", "nombre_accion", 19, 32, "SEARCH", {"nombre_accion":"Consultar"}, true),
   Array("accion", "descrip_accion", 20, 33, "ADD", {"descrip_accion":"desc"}, "descrip_accion_min_size_ko"),
   Array("accion", "descrip_accion", 20, 34, "ADD", {"descrip_accion":"Permite añadir registros."}, true),
   Array("accion", "descrip_accion", 21, 35, "EDIT", {"descrip_accion":"desc"}, "descrip_accion_min_size_ko"),
   Array("accion", "descrip_accion", 21, 36, "EDIT", {"descrip_accion":"Permite añadir registros."}, true),
   Array("accion", "descrip_accion", 22, 37, "ADD", {"descrip_accion":"ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd"}, "descrip_accion_max_size_ko"),
   Array("accion", "descrip_accion", 22, 38, "ADD", {"descrip_accion":"Acción que ejecuta el alta de nuevos datos."}, true),
   Array("accion", "descrip_accion", 23, 39, "EDIT", {"descrip_accion":"ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd"}, "descrip_accion_max_size_ko"),
   Array("accion", "descrip_accion", 23, 40, "EDIT", {"descrip_accion":"Acción que ejecuta el alta de nuevos datos."}, true),
   Array("accion", "descrip_accion", 24, 41, "SEARCH", {"descrip_accion":"ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd"}, "descrip_accion_max_size_ko"),
   Array("accion", "descrip_accion", 24, 42, "SEARCH", {"descrip_accion":"Acción que ejecuta el alta de nuevos datos."}, true),
   Array("accion", "descrip_accion", 25, 43, "ADD", {"descrip_accion":"Accion_123_fail"}, "descrip_accion_format_ko"),
   Array("accion", "descrip_accion", 25, 44, "ADD", {"descrip_accion":"Permite buscar, editar y borrar elementos."}, true),
   Array("accion", "descrip_accion", 26, 45, "EDIT", {"descrip_accion":"Accion_123_fail"}, "descrip_accion_format_ko"),
   Array("accion", "descrip_accion", 26, 46, "EDIT", {"descrip_accion":"Permite buscar, editar y borrar elementos."}, true),
   Array("accion", "descrip_accion", 27, 47, "SEARCH", {"descrip_accion":"Accion_123_fail"}, "descrip_accion_format_ko"),
   Array("accion", "descrip_accion", 27, 48, "SEARCH", {"descrip_accion":"Permite buscar, editar y borrar elementos."}, true),
   Array("accion", "descrip_accion", 28, 49, "ADD", {"descrip_accion":"Ejecuta la validación y guardado."}, true),
   Array("accion", "descrip_accion", 29, 50, "EDIT", {"descrip_accion":"Ejecuta la validación y guardado."}, true),
   Array("accion", "descrip_accion", 30, 51, "SEARCH", {"descrip_accion":"Ejecuta la validación y guardado."}, true)
);
