let funcionalidad_def_tests = Array(
   Array("funcionalidad", "id_funcionalidad", "input", 1, "cumple tamaño numerico minimo id_funcionalidad en ADD", "min_size", "ADD", "id_funcionalidad_min_size_ko", "Mínimo 1"),
   Array("funcionalidad", "id_funcionalidad", "input", 2, "cumple tamaño numerico minimo id_funcionalidad en EDIT", "min_size", "EDIT", "id_funcionalidad_min_size_ko", "Mínimo 1"),
   Array("funcionalidad", "id_funcionalidad", "input", 3, "cumple tamaño numerico maximo id_funcionalidad en ADD", "max_size", "ADD", "id_funcionalidad_max_size_ko", "Máximo 11"),
   Array("funcionalidad", "id_funcionalidad", "input", 4, "cumple tamaño numerico maximo id_funcionalidad en EDIT", "max_size", "EDIT", "id_funcionalidad_max_size_ko", "Máximo 11"),
   Array("funcionalidad", "id_funcionalidad", "input", 5, "cumple tamaño numerico maximo id_funcionalidad en SEARCH", "max_size", "SEARCH", "id_funcionalidad_max_size_ko", "Máximo 11"),
   Array("funcionalidad", "id_funcionalidad", "input", 6, "es correcto id_funcionalidad en ADD", "valid", "ADD", true, "ID funcionalidad correcto"),
   Array("funcionalidad", "id_funcionalidad", "input", 7, "es correcto id_funcionalidad en EDIT", "valid", "EDIT", true, "ID funcionalidad correcto"),
   Array("funcionalidad", "id_funcionalidad", "input", 8, "es correcto id_funcionalidad en SEARCH", "valid", "SEARCH", true, "ID funcionalidad correcto"),
   Array("funcionalidad", "nombre_funcionalidad", "input", 9, "cumple tamaño minimo nombre_funcionalidad en ADD", "min_size", "ADD", "nombre_funcionalidad_min_size_ko", "Nombre muy corto (min 5)"),
   Array("funcionalidad", "nombre_funcionalidad", "input", 10, "cumple tamaño minimo nombre_funcionalidad en EDIT", "min_size", "EDIT", "nombre_funcionalidad_min_size_ko", "Nombre muy corto (min 5)"),
   Array("funcionalidad", "nombre_funcionalidad", "input", 11, "cumple tamaño maximo nombre_funcionalidad en ADD", "max_size", "ADD", "nombre_funcionalidad_max_size_ko", "Nombre muy largo (max 48)"),
   Array("funcionalidad", "nombre_funcionalidad", "input", 12, "cumple tamaño maximo nombre_funcionalidad en EDIT", "max_size", "EDIT", "nombre_funcionalidad_max_size_ko", "Nombre muy largo (max 48)"),
   Array("funcionalidad", "nombre_funcionalidad", "input", 13, "cumple tamaño maximo nombre_funcionalidad en SEARCH", "max_size", "SEARCH", "nombre_funcionalidad_max_size_ko", "Nombre muy largo (max 48)"),
   Array("funcionalidad", "nombre_funcionalidad", "input", 14, "cumple formato alfabetico con ñ en ADD", "format", "ADD", "nombre_funcionalidad_format_ko", "Formato inválido"),
   Array("funcionalidad", "nombre_funcionalidad", "input", 15, "cumple formato alfabetico con ñ en EDIT", "format", "EDIT", "nombre_funcionalidad_format_ko", "Formato inválido"),
   Array("funcionalidad", "nombre_funcionalidad", "input", 16, "cumple formato alfabetico con ñ en SEARCH", "format", "SEARCH", "nombre_funcionalidad_format_ko", "Formato inválido"),
   Array("funcionalidad", "nombre_funcionalidad", "input", 17, "es correcto nombre_funcionalidad en ADD", "valid", "ADD", true, "Funcionalidad correcta"),
   Array("funcionalidad", "nombre_funcionalidad", "input", 18, "es correcto nombre_funcionalidad en EDIT", "valid", "EDIT", true, "Funcionalidad correcta"),
   Array("funcionalidad", "nombre_funcionalidad", "input", 19, "es correcto nombre_funcionalidad en SEARCH", "valid", "SEARCH", true, "Funcionalidad correcta"),
   Array("funcionalidad", "descrip_funcionalidad", "input", 20, "cumple tamaño minimo descrip_funcionalidad en ADD", "min_size", "ADD", "descrip_funcionalidad_min_size_ko", "Descripción muy corta (min 5)"),
   Array("funcionalidad", "descrip_funcionalidad", "input", 21, "cumple tamaño minimo descrip_funcionalidad en EDIT", "min_size", "EDIT", "descrip_funcionalidad_min_size_ko", "Descripción muy corta (min 5)"),
   Array("funcionalidad", "descrip_funcionalidad", "input", 22, "cumple tamaño maximo descrip_funcionalidad en ADD", "max_size", "ADD", "descrip_funcionalidad_max_size_ko", "Descripción muy larga (max 200)"),
   Array("funcionalidad", "descrip_funcionalidad", "input", 23, "cumple tamaño maximo descrip_funcionalidad en EDIT", "max_size", "EDIT", "descrip_funcionalidad_max_size_ko", "Descripción muy larga (max 200)"),
   Array("funcionalidad", "descrip_funcionalidad", "input", 24, "cumple tamaño maximo descrip_funcionalidad en SEARCH", "max_size", "SEARCH", "descrip_funcionalidad_max_size_ko", "Descripción muy larga (max 200)"),
   Array("funcionalidad", "descrip_funcionalidad", "input", 25, "cumple formato alfabetico con ñ, espacio y puntuacion en ADD", "format", "ADD", "descrip_funcionalidad_format_ko", "Formato inválido"),
   Array("funcionalidad", "descrip_funcionalidad", "input", 26, "cumple formato alfabetico con ñ, espacio y puntuacion en EDIT", "format", "EDIT", "descrip_funcionalidad_format_ko", "Formato inválido"),
   Array("funcionalidad", "descrip_funcionalidad", "input", 27, "cumple formato alfabetico con ñ, espacio y puntuacion en SEARCH", "format", "SEARCH", "descrip_funcionalidad_format_ko", "Formato inválido"),
   Array("funcionalidad", "descrip_funcionalidad", "input", 28, "es correcto descrip_funcionalidad en ADD", "valid", "ADD", true, "Descripción correcta"),
   Array("funcionalidad", "descrip_funcionalidad", "input", 29, "es correcto descrip_funcionalidad en EDIT", "valid", "EDIT", true, "Descripción correcta"),
   Array("funcionalidad", "descrip_funcionalidad", "input", 30, "es correcto descrip_funcionalidad en SEARCH", "valid", "SEARCH", true, "Descripción correcta")
);

let funcionalidad_pruebas = Array(
   Array("funcionalidad", "id_funcionalidad", 1, 1, "ADD", {"id_funcionalidad":0}, "id_funcionalidad_min_size_ko"),
   Array("funcionalidad", "id_funcionalidad", 1, 2, "ADD", {"id_funcionalidad":1}, true),
   Array("funcionalidad", "id_funcionalidad", 2, 3, "EDIT", {"id_funcionalidad":0}, "id_funcionalidad_min_size_ko"),
   Array("funcionalidad", "id_funcionalidad", 2, 4, "EDIT", {"id_funcionalidad":1}, true),
   Array("funcionalidad", "id_funcionalidad", 3, 5, "ADD", {"id_funcionalidad":12}, "id_funcionalidad_max_size_ko"),
   Array("funcionalidad", "id_funcionalidad", 3, 6, "ADD", {"id_funcionalidad":10}, true),
   Array("funcionalidad", "id_funcionalidad", 4, 7, "EDIT", {"id_funcionalidad":12}, "id_funcionalidad_max_size_ko"),
   Array("funcionalidad", "id_funcionalidad", 4, 8, "EDIT", {"id_funcionalidad":10}, true),
   Array("funcionalidad", "id_funcionalidad", 5, 9, "SEARCH", {"id_funcionalidad":12}, "id_funcionalidad_max_size_ko"),
   Array("funcionalidad", "id_funcionalidad", 5, 10, "SEARCH", {"id_funcionalidad":10}, true),
   Array("funcionalidad", "id_funcionalidad", 6, 11, "ADD", {"id_funcionalidad":2}, true),
   Array("funcionalidad", "id_funcionalidad", 7, 12, "EDIT", {"id_funcionalidad":2}, true),
   Array("funcionalidad", "id_funcionalidad", 8, 13, "SEARCH", {"id_funcionalidad":2}, true),
   Array("funcionalidad", "nombre_funcionalidad", 9, 14, "ADD", {"nombre_funcionalidad":"func"}, "nombre_funcionalidad_min_size_ko"),
   Array("funcionalidad", "nombre_funcionalidad", 9, 15, "ADD", {"nombre_funcionalidad":"Gestión"}, true),
   Array("funcionalidad", "nombre_funcionalidad", 10, 16, "EDIT", {"nombre_funcionalidad":"func"}, "nombre_funcionalidad_min_size_ko"),
   Array("funcionalidad", "nombre_funcionalidad", 10, 17, "EDIT", {"nombre_funcionalidad":"Gestión"}, true),
   Array("funcionalidad", "nombre_funcionalidad", 11, 18, "ADD", {"nombre_funcionalidad":"fffffffffffffffffffffffffffffffffffffffffffffffff"}, "nombre_funcionalidad_max_size_ko"),
   Array("funcionalidad", "nombre_funcionalidad", 11, 19, "ADD", {"nombre_funcionalidad":"Administración"}, true),
   Array("funcionalidad", "nombre_funcionalidad", 12, 20, "EDIT", {"nombre_funcionalidad":"fffffffffffffffffffffffffffffffffffffffffffffffff"}, "nombre_funcionalidad_max_size_ko"),
   Array("funcionalidad", "nombre_funcionalidad", 12, 21, "EDIT", {"nombre_funcionalidad":"Administración"}, true),
   Array("funcionalidad", "nombre_funcionalidad", 13, 22, "SEARCH", {"nombre_funcionalidad":"fffffffffffffffffffffffffffffffffffffffffffffffff"}, "nombre_funcionalidad_max_size_ko"),
   Array("funcionalidad", "nombre_funcionalidad", 13, 23, "SEARCH", {"nombre_funcionalidad":"Administración"}, true),
   Array("funcionalidad", "nombre_funcionalidad", 14, 24, "ADD", {"nombre_funcionalidad":"Gestion123"}, "nombre_funcionalidad_format_ko"),
   Array("funcionalidad", "nombre_funcionalidad", 14, 25, "ADD", {"nombre_funcionalidad":"Mantenimiento"}, true),
   Array("funcionalidad", "nombre_funcionalidad", 15, 26, "EDIT", {"nombre_funcionalidad":"Gestion123"}, "nombre_funcionalidad_format_ko"),
   Array("funcionalidad", "nombre_funcionalidad", 15, 27, "EDIT", {"nombre_funcionalidad":"Mantenimiento"}, true),
   Array("funcionalidad", "nombre_funcionalidad", 16, 28, "SEARCH", {"nombre_funcionalidad":"Gestion123"}, "nombre_funcionalidad_format_ko"),
   Array("funcionalidad", "nombre_funcionalidad", 16, 29, "SEARCH", {"nombre_funcionalidad":"Mantenimiento"}, true),
   Array("funcionalidad", "nombre_funcionalidad", 17, 30, "ADD", {"nombre_funcionalidad":"Estadísticas"}, true),
   Array("funcionalidad", "nombre_funcionalidad", 18, 31, "EDIT", {"nombre_funcionalidad":"Estadísticas"}, true),
   Array("funcionalidad", "nombre_funcionalidad", 19, 32, "SEARCH", {"nombre_funcionalidad":"Estadísticas"}, true),
   Array("funcionalidad", "descrip_funcionalidad", 20, 33, "ADD", {"descrip_funcionalidad":"desc"}, "descrip_funcionalidad_min_size_ko"),
   Array("funcionalidad", "descrip_funcionalidad", 20, 34, "ADD", {"descrip_funcionalidad":"Módulo de gestión general."}, true),
   Array("funcionalidad", "descrip_funcionalidad", 21, 35, "EDIT", {"descrip_funcionalidad":"desc"}, "descrip_funcionalidad_min_size_ko"),
   Array("funcionalidad", "descrip_funcionalidad", 21, 36, "EDIT", {"descrip_funcionalidad":"Módulo de gestión general."}, true),
   Array("funcionalidad", "descrip_funcionalidad", 22, 37, "ADD", {"descrip_funcionalidad":"fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"}, "descrip_funcionalidad_max_size_ko"),
   Array("funcionalidad", "descrip_funcionalidad", 22, 38, "ADD", {"descrip_funcionalidad":"Módulo encargado del seguimiento."}, true),
   Array("funcionalidad", "descrip_funcionalidad", 23, 39, "EDIT", {"descrip_funcionalidad":"fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"}, "descrip_funcionalidad_max_size_ko"),
   Array("funcionalidad", "descrip_funcionalidad", 23, 40, "EDIT", {"descrip_funcionalidad":"Módulo encargado del seguimiento."}, true),
   Array("funcionalidad", "descrip_funcionalidad", 24, 41, "SEARCH", {"descrip_funcionalidad":"fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"}, "descrip_funcionalidad_max_size_ko"),
   Array("funcionalidad", "descrip_funcionalidad", 24, 42, "SEARCH", {"descrip_funcionalidad":"Módulo encargado del seguimiento."}, true),
   Array("funcionalidad", "descrip_funcionalidad", 25, 43, "ADD", {"descrip_funcionalidad":"Modulo_123_bad"}, "descrip_funcionalidad_format_ko"),
   Array("funcionalidad", "descrip_funcionalidad", 25, 44, "ADD", {"descrip_funcionalidad":"Configuración de parámetros."}, true),
   Array("funcionalidad", "descrip_funcionalidad", 26, 45, "EDIT", {"descrip_funcionalidad":"Modulo_123_bad"}, "descrip_funcionalidad_format_ko"),
   Array("funcionalidad", "descrip_funcionalidad", 26, 46, "EDIT", {"descrip_funcionalidad":"Configuración de parámetros."}, true),
   Array("funcionalidad", "descrip_funcionalidad", 27, 47, "SEARCH", {"descrip_funcionalidad":"Modulo_123_bad"}, "descrip_funcionalidad_format_ko"),
   Array("funcionalidad", "descrip_funcionalidad", 27, 48, "SEARCH", {"descrip_funcionalidad":"Configuración de parámetros."}, true),
   Array("funcionalidad", "descrip_funcionalidad", 28, 49, "ADD", {"descrip_funcionalidad":"Control de acceso y permisos."}, true),
   Array("funcionalidad", "descrip_funcionalidad", 29, 50, "EDIT", {"descrip_funcionalidad":"Control de acceso y permisos."}, true),
   Array("funcionalidad", "descrip_funcionalidad", 30, 51, "SEARCH", {"descrip_funcionalidad":"Control de acceso y permisos."}, true)
);
