let persona_def_tests = Array(
   Array("persona", "dni", "input", 1, "cumple tamaño minimo dni en ADD", "min_size", "ADD", "dni_min_size_ko", "DNI demasiado corto (min 9)"),
   Array("persona", "dni", "input", 2, "cumple tamaño minimo dni en EDIT", "min_size", "EDIT", "dni_min_size_ko", "DNI demasiado corto (min 9)"),
   Array("persona", "dni", "input", 3, "cumple tamaño maximo dni en ADD", "max_size", "ADD", "dni_max_size_ko", "DNI demasiado largo (max 9)"),
   Array("persona", "dni", "input", 4, "cumple tamaño maximo dni en EDIT", "max_size", "EDIT", "dni_max_size_ko", "DNI demasiado largo (max 9)"),
   Array("persona", "dni", "input", 5, "cumple tamaño maximo dni en SEARCH", "max_size", "SEARCH", "dni_max_size_ko", "DNI demasiado largo (max 9)"),
   Array("persona", "dni", "input", 6, "cumple formato dni en ADD", "format", "ADD", "dni_format_ko", "Formato DNI inválido"),
   Array("persona", "dni", "input", 7, "cumple formato dni en EDIT", "format", "EDIT", "dni_format_ko", "Formato DNI inválido"),
   Array("persona", "dni", "input", 8, "cumple formato dni en SEARCH", "format", "SEARCH", "dni_format_ko", "Formato DNI inválido"),
   Array("persona", "dni", "input", 9, "es correcto dni en ADD", "valid", "ADD", true, "DNI correcto"),
   Array("persona", "dni", "input", 10, "es correcto dni en EDIT", "valid", "EDIT", true, "DNI correcto"),
   Array("persona", "dni", "input", 11, "es correcto dni en SEARCH", "valid", "SEARCH", true, "DNI correcto"),
   Array("persona", "nombre_persona", "input", 12, "cumple tamaño minimo nombre_persona en ADD", "min_size", "ADD", "nombre_persona_min_size_ko", "Nombre muy corto (min 2)"),
   Array("persona", "nombre_persona", "input", 13, "cumple tamaño minimo nombre_persona en EDIT", "min_size", "EDIT", "nombre_persona_min_size_ko", "Nombre muy corto (min 2)"),
   Array("persona", "nombre_persona", "input", 14, "cumple tamaño maximo nombre_persona en ADD", "max_size", "ADD", "nombre_persona_max_size_ko", "Nombre muy largo (max 45)"),
   Array("persona", "nombre_persona", "input", 15, "cumple tamaño maximo nombre_persona en EDIT", "max_size", "EDIT", "nombre_persona_max_size_ko", "Nombre muy largo (max 45)"),
   Array("persona", "nombre_persona", "input", 16, "cumple tamaño maximo nombre_persona en SEARCH", "max_size", "SEARCH", "nombre_persona_max_size_ko", "Nombre muy largo (max 45)"),
   Array("persona", "nombre_persona", "input", 17, "cumple formato nombre con ñ y acentos en ADD", "format", "ADD", "nombre_persona_format_ko", "Formato de nombre inválido"),
   Array("persona", "nombre_persona", "input", 18, "cumple formato nombre con ñ y acentos en EDIT", "format", "EDIT", "nombre_persona_format_ko", "Formato de nombre inválido"),
   Array("persona", "nombre_persona", "input", 19, "cumple formato nombre con ñ y acentos en SEARCH", "format", "SEARCH", "nombre_persona_format_ko", "Formato de nombre inválido"),
   Array("persona", "nombre_persona", "input", 20, "es correcto nombre_persona en ADD", "valid", "ADD", true, "Nombre correcto"),
   Array("persona", "nombre_persona", "input", 21, "es correcto nombre_persona en EDIT", "valid", "EDIT", true, "Nombre correcto"),
   Array("persona", "nombre_persona", "input", 22, "es correcto nombre_persona en SEARCH", "valid", "SEARCH", true, "Nombre correcto"),
   Array("persona", "apellidos_persona", "input", 23, "cumple tamaño minimo apellidos_persona en ADD", "min_size", "ADD", "apellidos_persona_min_size_ko", "Apellidos muy cortos (min 3)"),
   Array("persona", "apellidos_persona", "input", 24, "cumple tamaño minimo apellidos_persona en EDIT", "min_size", "EDIT", "apellidos_persona_min_size_ko", "Apellidos muy cortos (min 3)"),
   Array("persona", "apellidos_persona", "input", 25, "cumple tamaño maximo apellidos_persona en ADD", "max_size", "ADD", "apellidos_persona_max_size_ko", "Apellidos muy largos (max 100)"),
   Array("persona", "apellidos_persona", "input", 26, "cumple tamaño maximo apellidos_persona en EDIT", "max_size", "EDIT", "apellidos_persona_max_size_ko", "Apellidos muy largos (max 100)"),
   Array("persona", "apellidos_persona", "input", 27, "cumple tamaño maximo apellidos_persona en SEARCH", "max_size", "SEARCH", "apellidos_persona_max_size_ko", "Apellidos muy largos (max 100)"),
   Array("persona", "apellidos_persona", "input", 28, "cumple formato apellidos en ADD", "format", "ADD", "apellidos_persona_format_ko", "Formato de apellidos inválido"),
   Array("persona", "apellidos_persona", "input", 29, "cumple formato apellidos en EDIT", "format", "EDIT", "apellidos_persona_format_ko", "Formato de apellidos inválido"),
   Array("persona", "apellidos_persona", "input", 30, "cumple formato apellidos en SEARCH", "format", "SEARCH", "apellidos_persona_format_ko", "Formato de apellidos inválido"),
   Array("persona", "apellidos_persona", "input", 31, "es correcto apellidos_persona en ADD", "valid", "ADD", true, "Apellidos correctos"),
   Array("persona", "apellidos_persona", "input", 32, "es correcto apellidos_persona en EDIT", "valid", "EDIT", true, "Apellidos correctos"),
   Array("persona", "apellidos_persona", "input", 33, "es correcto apellidos_persona en SEARCH", "valid", "SEARCH", true, "Apellidos correctos"),
   Array("persona", "fechaNacimiento_persona", "input", 34, "cumple formato fecha dd/mm/aaaa en ADD", "format", "ADD", "fechaNacimiento_persona_format_ko", "Formato fecha inválido"),
   Array("persona", "fechaNacimiento_persona", "input", 35, "cumple formato fecha dd/mm/aaaa en EDIT", "format", "EDIT", "fechaNacimiento_persona_format_ko", "Formato fecha inválido"),
   Array("persona", "fechaNacimiento_persona", "input", 36, "cumple formato fecha dd/mm/aaaa en SEARCH", "format", "SEARCH", "fechaNacimiento_persona_format_ko", "Formato fecha inválido"),
   Array("persona", "fechaNacimiento_persona", "input", 37, "es correcto fechaNacimiento_persona en ADD", "valid", "ADD", true, "Fecha correcta"),
   Array("persona", "fechaNacimiento_persona", "input", 38, "es correcto fechaNacimiento_persona en EDIT", "valid", "EDIT", true, "Fecha correcta"),
   Array("persona", "fechaNacimiento_persona", "input", 39, "es correcto fechaNacimiento_persona en SEARCH", "valid", "SEARCH", true, "Fecha correcta"),
   Array("persona", "direccion_persona", "input", 40, "cumple tamaño minimo direccion_persona en ADD", "min_size", "ADD", "direccion_persona_min_size_ko", "Dirección muy corta (min 10)"),
   Array("persona", "direccion_persona", "input", 41, "cumple tamaño minimo direccion_persona en EDIT", "min_size", "EDIT", "direccion_persona_min_size_ko", "Dirección muy corta (min 10)"),
   Array("persona", "direccion_persona", "input", 42, "cumple tamaño maximo direccion_persona en ADD", "max_size", "ADD", "direccion_persona_max_size_ko", "Dirección muy larga (max 200)"),
   Array("persona", "direccion_persona", "input", 43, "cumple tamaño maximo direccion_persona en EDIT", "max_size", "EDIT", "direccion_persona_max_size_ko", "Dirección muy larga (max 200)"),
   Array("persona", "direccion_persona", "input", 44, "cumple tamaño maximo direccion_persona en SEARCH", "max_size", "SEARCH", "direccion_persona_max_size_ko", "Dirección muy larga (max 200)"),
   Array("persona", "direccion_persona", "input", 45, "cumple formato direccion en ADD", "format", "ADD", "direccion_persona_format_ko", "Formato dirección inválido"),
   Array("persona", "direccion_persona", "input", 46, "cumple formato direccion en EDIT", "format", "EDIT", "direccion_persona_format_ko", "Formato dirección inválido"),
   Array("persona", "direccion_persona", "input", 47, "cumple formato direccion en SEARCH", "format", "SEARCH", "direccion_persona_format_ko", "Formato dirección inválido"),
   Array("persona", "direccion_persona", "input", 48, "es correcto direccion_persona en ADD", "valid", "ADD", true, "Dirección correcta"),
   Array("persona", "direccion_persona", "input", 49, "es correcto direccion_persona en EDIT", "valid", "EDIT", true, "Dirección correcta"),
   Array("persona", "direccion_persona", "input", 50, "es correcto direccion_persona en SEARCH", "valid", "SEARCH", true, "Dirección correcta"),
   Array("persona", "telefono_persona", "input", 51, "cumple tamaño minimo telefono_persona en ADD", "min_size", "ADD", "telefono_persona_min_size_ko", "Teléfono muy corto (min 9)"),
   Array("persona", "telefono_persona", "input", 52, "cumple tamaño minimo telefono_persona en EDIT", "min_size", "EDIT", "telefono_persona_min_size_ko", "Teléfono muy corto (min 9)"),
   Array("persona", "telefono_persona", "input", 53, "cumple formato telefono valido en ADD", "format", "ADD", "telefono_persona_format_ko", "Formato teléfono inválido"),
   Array("persona", "telefono_persona", "input", 54, "cumple formato telefono valido en EDIT", "format", "EDIT", "telefono_persona_format_ko", "Formato teléfono inválido"),
   Array("persona", "telefono_persona", "input", 55, "cumple formato telefono valido en SEARCH", "format", "SEARCH", "telefono_persona_format_ko", "Formato teléfono inválido"),
   Array("persona", "telefono_persona", "input", 56, "es correcto telefono_persona en ADD", "valid", "ADD", true, "Teléfono correcto"),
   Array("persona", "telefono_persona", "input", 57, "es correcto telefono_persona en EDIT", "valid", "EDIT", true, "Teléfono correcto"),
   Array("persona", "telefono_persona", "input", 58, "es correcto telefono_persona en SEARCH", "valid", "SEARCH", true, "Teléfono correcto"),
   Array("persona", "email_persona", "input", 59, "cumple formato email valido en ADD", "format", "ADD", "email_persona_format_ko", "Formato email inválido"),
   Array("persona", "email_persona", "input", 60, "cumple formato email valido en EDIT", "format", "EDIT", "email_persona_format_ko", "Formato email inválido"),
   Array("persona", "email_persona", "input", 61, "cumple formato email valido en SEARCH", "format", "SEARCH", "email_persona_format_ko", "Formato email inválido"),
   Array("persona", "email_persona", "input", 62, "es correcto email_persona en ADD", "valid", "ADD", true, "Email correcto"),
   Array("persona", "email_persona", "input", 63, "es correcto email_persona en EDIT", "valid", "EDIT", true, "Email correcto"),
   Array("persona", "email_persona", "input", 64, "es correcto email_persona en SEARCH", "valid", "SEARCH", true, "Email correcto"),
   Array("persona", "foto_persona", "file", 65, "existe fichero foto_persona en ADD", "exist_file", "ADD", "foto_persona_exist_file_ko", "Debe seleccionar un fichero jpg o jpeg"),
   Array("persona", "foto_persona", "file", 66, "cumple formato nombre foto_persona en ADD", "format_name_file", "ADD", "foto_persona_format_name_file_ko", "Nombre de archivo de foto inválido"),
   Array("persona", "foto_persona", "file", 67, "cumple formato nombre foto_persona en EDIT", "format_name_file", "EDIT", "foto_persona_format_name_file_ko", "Nombre de archivo de foto inválido"),
   Array("persona", "foto_persona", "input", 68, "cumple formato nombre foto_persona en SEARCH", "format_name_file", "SEARCH", "foto_persona_format_name_file_ko", "Nombre de archivo de foto inválido"),
   Array("persona", "foto_persona", "file", 69, "es correcto foto_persona en ADD", "valid", "ADD", true, "Foto correcta"),
   Array("persona", "foto_persona", "file", 70, "es correcto foto_persona en EDIT", "valid", "EDIT", true, "Foto correcta"),
   Array("persona", "foto_persona", "input", 71, "es correcto foto_persona en SEARCH", "valid", "SEARCH", true, "Foto correcta")
);

let persona_pruebas = Array(
   Array("persona", "dni", 1, 1, "ADD", {"dni":"1234"}, "dni_min_size_ko"),
   Array("persona", "dni", 1, 2, "ADD", {"dni":"12345678Z"}, true),
   Array("persona", "dni", 2, 3, "EDIT", {"dni":"1234"}, "dni_min_size_ko"),
   Array("persona", "dni", 2, 4, "EDIT", {"dni":"12345678Z"}, true),
   Array("persona", "dni", 3, 5, "ADD", {"dni":"1234567890"}, "dni_max_size_ko"),
   Array("persona", "dni", 3, 6, "ADD", {"dni":"12345678Z"}, true),
   Array("persona", "dni", 4, 7, "EDIT", {"dni":"1234567890"}, "dni_max_size_ko"),
   Array("persona", "dni", 4, 8, "EDIT", {"dni":"12345678Z"}, true),
   Array("persona", "dni", 5, 9, "SEARCH", {"dni":"1234567890"}, "dni_max_size_ko"),
   Array("persona", "dni", 5, 10, "SEARCH", {"dni":"12345678Z"}, true),
   Array("persona", "dni", 6, 11, "ADD", {"dni":"12345678A"}, "dni_format_ko"),
   Array("persona", "dni", 6, 12, "ADD", {"dni":"12345678Z"}, true),
   Array("persona", "dni", 7, 13, "EDIT", {"dni":"12345678A"}, "dni_format_ko"),
   Array("persona", "dni", 7, 14, "EDIT", {"dni":"12345678Z"}, true),
   Array("persona", "dni", 8, 15, "SEARCH", {"dni":"12345678A"}, "dni_format_ko"),
   Array("persona", "dni", 8, 16, "SEARCH", {"dni":"12345678Z"}, true),
   Array("persona", "dni", 9, 17, "ADD", {"dni":"80423097D"}, true),
   Array("persona", "dni", 10, 18, "EDIT", {"dni":"80423097D"}, true),
   Array("persona", "dni", 11, 19, "SEARCH", {"dni":"80423097D"}, true),
   Array("persona", "nombre_persona", 12, 20, "ADD", {"nombre_persona":"A"}, "nombre_persona_min_size_ko"),
   Array("persona", "nombre_persona", 12, 21, "ADD", {"nombre_persona":"Iñaqui"}, true),
   Array("persona", "nombre_persona", 13, 22, "EDIT", {"nombre_persona":"A"}, "nombre_persona_min_size_ko"),
   Array("persona", "nombre_persona", 13, 23, "EDIT", {"nombre_persona":"Iñaqui"}, true),
   Array("persona", "nombre_persona", 14, 24, "ADD", {"nombre_persona":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"}, "nombre_persona_max_size_ko"),
   Array("persona", "nombre_persona", 14, 25, "ADD", {"nombre_persona":"María-José"}, true),
   Array("persona", "nombre_persona", 15, 26, "EDIT", {"nombre_persona":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"}, "nombre_persona_max_size_ko"),
   Array("persona", "nombre_persona", 15, 27, "EDIT", {"nombre_persona":"María-José"}, true),
   Array("persona", "nombre_persona", 16, 28, "SEARCH", {"nombre_persona":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"}, "nombre_persona_max_size_ko"),
   Array("persona", "nombre_persona", 16, 29, "SEARCH", {"nombre_persona":"María-José"}, true),
   Array("persona", "nombre_persona", 17, 30, "ADD", {"nombre_persona":"Juan123"}, "nombre_persona_format_ko"),
   Array("persona", "nombre_persona", 17, 31, "ADD", {"nombre_persona":"Begoña"}, true),
   Array("persona", "nombre_persona", 18, 32, "EDIT", {"nombre_persona":"Juan123"}, "nombre_persona_format_ko"),
   Array("persona", "nombre_persona", 18, 33, "EDIT", {"nombre_persona":"Begoña"}, true),
   Array("persona", "nombre_persona", 19, 34, "SEARCH", {"nombre_persona":"Juan123"}, "nombre_persona_format_ko"),
   Array("persona", "nombre_persona", 19, 35, "SEARCH", {"nombre_persona":"Begoña"}, true),
   Array("persona", "nombre_persona", 20, 36, "ADD", {"nombre_persona":"Ángela M.ª"}, true),
   Array("persona", "nombre_persona", 21, 37, "EDIT", {"nombre_persona":"Ángela M.ª"}, true),
   Array("persona", "nombre_persona", 22, 38, "SEARCH", {"nombre_persona":"Ángela M.ª"}, true),
   Array("persona", "apellidos_persona", 23, 39, "ADD", {"apellidos_persona":"Oz"}, "apellidos_persona_min_size_ko"),
   Array("persona", "apellidos_persona", 23, 40, "ADD", {"apellidos_persona":"Pérez"}, true),
   Array("persona", "apellidos_persona", 24, 41, "EDIT", {"apellidos_persona":"Oz"}, "apellidos_persona_min_size_ko"),
   Array("persona", "apellidos_persona", 24, 42, "EDIT", {"apellidos_persona":"Pérez"}, true),
   Array("persona", "apellidos_persona", 25, 43, "ADD", {"apellidos_persona":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"}, "apellidos_persona_max_size_ko"),
   Array("persona", "apellidos_persona", 25, 44, "ADD", {"apellidos_persona":"Gómez-Núñez"}, true),
   Array("persona", "apellidos_persona", 26, 45, "EDIT", {"apellidos_persona":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"}, "apellidos_persona_max_size_ko"),
   Array("persona", "apellidos_persona", 26, 46, "EDIT", {"apellidos_persona":"Gómez-Núñez"}, true),
   Array("persona", "apellidos_persona", 27, 47, "SEARCH", {"apellidos_persona":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"}, "apellidos_persona_max_size_ko"),
   Array("persona", "apellidos_persona", 27, 48, "SEARCH", {"apellidos_persona":"Gómez-Núñez"}, true),
   Array("persona", "apellidos_persona", 28, 49, "ADD", {"apellidos_persona":"Pérez_123"}, "apellidos_persona_format_ko"),
   Array("persona", "apellidos_persona", 28, 50, "ADD", {"apellidos_persona":"D'Arcy-Martínez Jr."}, true),
   Array("persona", "apellidos_persona", 29, 51, "EDIT", {"apellidos_persona":"Pérez_123"}, "apellidos_persona_format_ko"),
   Array("persona", "apellidos_persona", 29, 52, "EDIT", {"apellidos_persona":"D'Arcy-Martínez Jr."}, true),
   Array("persona", "apellidos_persona", 30, 53, "SEARCH", {"apellidos_persona":"Pérez_123"}, "apellidos_persona_format_ko"),
   Array("persona", "apellidos_persona", 30, 54, "SEARCH", {"apellidos_persona":"D'Arcy-Martínez Jr."}, true),
   Array("persona", "apellidos_persona", 31, 55, "ADD", {"apellidos_persona":"Núñez Rodríguez"}, true),
   Array("persona", "apellidos_persona", 32, 56, "EDIT", {"apellidos_persona":"Núñez Rodríguez"}, true),
   Array("persona", "apellidos_persona", 33, 57, "SEARCH", {"apellidos_persona":"Núñez Rodríguez"}, true),
   Array("persona", "fechaNacimiento_persona", 34, 58, "ADD", {"fechaNacimiento_persona":"2026-09-23"}, "fechaNacimiento_persona_format_ko"),
   Array("persona", "fechaNacimiento_persona", 34, 59, "ADD", {"fechaNacimiento_persona":"15/08/2000"}, true),
   Array("persona", "fechaNacimiento_persona", 35, 60, "EDIT", {"fechaNacimiento_persona":"2026-09-23"}, "fechaNacimiento_persona_format_ko"),
   Array("persona", "fechaNacimiento_persona", 35, 61, "EDIT", {"fechaNacimiento_persona":"15/08/2000"}, true),
   Array("persona", "fechaNacimiento_persona", 36, 62, "SEARCH", {"fechaNacimiento_persona":"2026-09-23"}, "fechaNacimiento_persona_format_ko"),
   Array("persona", "fechaNacimiento_persona", 36, 63, "SEARCH", {"fechaNacimiento_persona":"15/08/2000"}, true),
   Array("persona", "fechaNacimiento_persona", 37, 64, "ADD", {"fechaNacimiento_persona":"20/11/1998"}, true),
   Array("persona", "fechaNacimiento_persona", 38, 65, "EDIT", {"fechaNacimiento_persona":"20/11/1998"}, true),
   Array("persona", "fechaNacimiento_persona", 39, 66, "SEARCH", {"fechaNacimiento_persona":"20/11/1998"}, true),
   Array("persona", "direccion_persona", 40, 67, "ADD", {"direccion_persona":"C/ Mayor"}, "direccion_persona_min_size_ko"),
   Array("persona", "direccion_persona", 40, 68, "ADD", {"direccion_persona":"Av. España, 12; 3ºB"}, true),
   Array("persona", "direccion_persona", 41, 69, "EDIT", {"direccion_persona":"C/ Mayor"}, "direccion_persona_min_size_ko"),
   Array("persona", "direccion_persona", 41, 70, "EDIT", {"direccion_persona":"Av. España, 12; 3ºB"}, true),
   Array("persona", "direccion_persona", 42, 71, "ADD", {"direccion_persona":"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD"}, "direccion_persona_max_size_ko"),
   Array("persona", "direccion_persona", 42, 72, "ADD", {"direccion_persona":"C/ Begoña n.º 4 / 2ºA"}, true),
   Array("persona", "direccion_persona", 43, 73, "EDIT", {"direccion_persona":"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD"}, "direccion_persona_max_size_ko"),
   Array("persona", "direccion_persona", 43, 74, "EDIT", {"direccion_persona":"C/ Begoña n.º 4 / 2ºA"}, true),
   Array("persona", "direccion_persona", 44, 75, "SEARCH", {"direccion_persona":"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD"}, "direccion_persona_max_size_ko"),
   Array("persona", "direccion_persona", 44, 76, "SEARCH", {"direccion_persona":"C/ Begoña n.º 4 / 2ºA"}, true),
   Array("persona", "direccion_persona", 45, 77, "ADD", {"direccion_persona":"C/ Mayor @ #"}, "direccion_persona_format_ko"),
   Array("persona", "direccion_persona", 45, 78, "ADD", {"direccion_persona":"C/ Pi y Margall, 45; 1º - Pza. España / Rúa Begoña"}, true),
   Array("persona", "direccion_persona", 46, 79, "EDIT", {"direccion_persona":"C/ Mayor @ #"}, "direccion_persona_format_ko"),
   Array("persona", "direccion_persona", 46, 80, "EDIT", {"direccion_persona":"C/ Pi y Margall, 45; 1º - Pza. España / Rúa Begoña"}, true),
   Array("persona", "direccion_persona", 47, 81, "SEARCH", {"direccion_persona":"C/ Mayor @ #"}, "direccion_persona_format_ko"),
   Array("persona", "direccion_persona", 47, 82, "SEARCH", {"direccion_persona":"C/ Pi y Margall, 45; 1º - Pza. España / Rúa Begoña"}, true),
   Array("persona", "direccion_persona", 48, 83, "ADD", {"direccion_persona":"Rúa das Aflitas, 12; 4ºA / Vigo"}, true),
   Array("persona", "direccion_persona", 49, 84, "EDIT", {"direccion_persona":"Rúa das Aflitas, 12; 4ºA / Vigo"}, true),
   Array("persona", "direccion_persona", 50, 85, "SEARCH", {"direccion_persona":"Rúa das Aflitas, 12; 4ºA / Vigo"}, true),
   Array("persona", "telefono_persona", 51, 86, "ADD", {"telefono_persona":"6001122"}, "telefono_persona_min_size_ko"),
   Array("persona", "telefono_persona", 51, 87, "ADD", {"telefono_persona":"986123456"}, true),
   Array("persona", "telefono_persona", 52, 88, "EDIT", {"telefono_persona":"6001122"}, "telefono_persona_min_size_ko"),
   Array("persona", "telefono_persona", 52, 89, "EDIT", {"telefono_persona":"986123456"}, true),
   Array("persona", "telefono_persona", 53, 90, "ADD", {"telefono_persona":"98612345A"}, "telefono_persona_format_ko"),
   Array("persona", "telefono_persona", 53, 91, "ADD", {"telefono_persona":"612345678"}, true),
   Array("persona", "telefono_persona", 54, 92, "EDIT", {"telefono_persona":"98612345A"}, "telefono_persona_format_ko"),
   Array("persona", "telefono_persona", 54, 93, "EDIT", {"telefono_persona":"612345678"}, true),
   Array("persona", "telefono_persona", 55, 94, "SEARCH", {"telefono_persona":"98612345A"}, "telefono_persona_format_ko"),
   Array("persona", "telefono_persona", 55, 95, "SEARCH", {"telefono_persona":"612345678"}, true),
   Array("persona", "telefono_persona", 56, 96, "ADD", {"telefono_persona":"988112233"}, true),
   Array("persona", "telefono_persona", 57, 97, "EDIT", {"telefono_persona":"988112233"}, true),
   Array("persona", "telefono_persona", 58, 98, "SEARCH", {"telefono_persona":"988112233"}, true),
   Array("persona", "email_persona", 59, 99, "ADD", {"email_persona":"correo_invalido.com"}, "email_persona_format_ko"),
   Array("persona", "email_persona", 59, 100, "ADD", {"email_persona":"usuario@uvigo.es"}, true),
   Array("persona", "email_persona", 60, 101, "EDIT", {"email_persona":"correo_invalido.com"}, "email_persona_format_ko"),
   Array("persona", "email_persona", 60, 102, "EDIT", {"email_persona":"usuario@uvigo.es"}, true),
   Array("persona", "email_persona", 61, 103, "SEARCH", {"email_persona":"correo_invalido.com"}, "email_persona_format_ko"),
   Array("persona", "email_persona", 61, 104, "SEARCH", {"email_persona":"usuario@uvigo.es"}, true),
   Array("persona", "email_persona", 62, 105, "ADD", {"email_persona":"alumno.proyectos@esei.uvigo.gal"}, true),
   Array("persona", "email_persona", 63, 106, "EDIT", {"email_persona":"alumno.proyectos@esei.uvigo.gal"}, true),
   Array("persona", "email_persona", 64, 107, "SEARCH", {"email_persona":"alumno.proyectos@esei.uvigo.gal"}, true),
   Array("persona", "foto_persona", 65, 108, "ADD", {}, "foto_persona_exist_file_ko"),
   Array("persona", "foto_persona", 65, 109, "ADD", {"foto_persona":"foto.jpg"}, true),
   Array("persona", "foto_persona", 66, 110, "ADD", {"foto_persona":"foto*.jpg"}, "foto_persona_format_name_file_ko"),
   Array("persona", "foto_persona", 66, 111, "ADD", {"foto_persona":"miFoto.jpg"}, true),
   Array("persona", "foto_persona", 67, 112, "EDIT", {"foto_persona":"foto*.jpg"}, "foto_persona_format_name_file_ko"),
   Array("persona", "foto_persona", 67, 113, "EDIT", {"foto_persona":"miFoto.jpg"}, true),
   Array("persona", "foto_persona", 68, 114, "SEARCH", {"foto_persona":"foto*.jpg"}, "foto_persona_format_name_file_ko"),
   Array("persona", "foto_persona", 68, 115, "SEARCH", {"foto_persona":"miFoto.jpg"}, true),
   Array("persona", "foto_persona", 69, 116, "ADD", {"foto_persona":"perfil.jpg"}, true),
   Array("persona", "foto_persona", 70, 117, "EDIT", {"foto_persona":"perfil.jpg"}, true),
   Array("persona", "foto_persona", 71, 118, "SEARCH", {"foto_persona":"perfil.jpg"}, true)
);
