let rol_def_tests = Array(
   Array("rol", "id_rol", "input", 1, "cumple tamaño numerico minimo id_rol en ADD", "min_size", "ADD", "id_rol_min_size_ko", "Mínimo 1"),
   Array("rol", "id_rol", "input", 2, "cumple tamaño numerico minimo id_rol en EDIT", "min_size", "EDIT", "id_rol_min_size_ko", "Mínimo 1"),
   Array("rol", "id_rol", "input", 3, "cumple tamaño numerico maximo id_rol en ADD", "max_size", "ADD", "id_rol_max_size_ko", "Máximo 11"),
   Array("rol", "id_rol", "input", 4, "cumple tamaño numerico maximo id_rol en EDIT", "max_size", "EDIT", "id_rol_max_size_ko", "Máximo 11"),
   Array("rol", "id_rol", "input", 5, "cumple tamaño numerico maximo id_rol en SEARCH", "max_size", "SEARCH", "id_rol_max_size_ko", "Máximo 11"),
   Array("rol", "id_rol", "input", 6, "es correcto id_rol en ADD", "valid", "ADD", true, "ID rol correcto"),
   Array("rol", "id_rol", "input", 7, "es correcto id_rol en EDIT", "valid", "EDIT", true, "ID rol correcto"),
   Array("rol", "id_rol", "input", 8, "es correcto id_rol en SEARCH", "valid", "SEARCH", true, "ID rol correcto"),
   Array("rol", "rol_name", "input", 9, "cumple tamaño minimo rol_name en ADD", "min_size", "ADD", "rol_name_min_size_ko", "Nombre muy corto (min 5)"),
   Array("rol", "rol_name", "input", 10, "cumple tamaño minimo rol_name en EDIT", "min_size", "EDIT", "rol_name_min_size_ko", "Nombre muy corto (min 5)"),
   Array("rol", "rol_name", "input", 11, "cumple tamaño maximo rol_name en ADD", "max_size", "ADD", "rol_name_max_size_ko", "Nombre muy largo (max 48)"),
   Array("rol", "rol_name", "input", 12, "cumple tamaño maximo rol_name en EDIT", "max_size", "EDIT", "rol_name_max_size_ko", "Nombre muy largo (max 48)"),
   Array("rol", "rol_name", "input", 13, "cumple tamaño maximo rol_name en SEARCH", "max_size", "SEARCH", "rol_name_max_size_ko", "Nombre muy largo (max 48)"),
   Array("rol", "rol_name", "input", 14, "cumple formato alfabetico en ADD", "format", "ADD", "rol_name_format_ko", "Formato inválido"),
   Array("rol", "rol_name", "input", 15, "cumple formato alfabetico en EDIT", "format", "EDIT", "rol_name_format_ko", "Formato inválido"),
   Array("rol", "rol_name", "input", 16, "cumple formato alfabetico en SEARCH", "format", "SEARCH", "rol_name_format_ko", "Formato inválido"),
   Array("rol", "rol_name", "input", 17, "es correcto rol_name en ADD", "valid", "ADD", true, "Rol name correcto"),
   Array("rol", "rol_name", "input", 18, "es correcto rol_name en EDIT", "valid", "EDIT", true, "Rol name correcto"),
   Array("rol", "rol_name", "input", 19, "es correcto rol_name en SEARCH", "valid", "SEARCH", true, "Rol name correcto"),
   Array("rol", "rol_description", "input", 20, "cumple tamaño minimo rol_description en ADD", "min_size", "ADD", "rol_description_min_size_ko", "Descripción muy corta (min 5)"),
   Array("rol", "rol_description", "input", 21, "cumple tamaño minimo rol_description en EDIT", "min_size", "EDIT", "rol_description_min_size_ko", "Descripción muy corta (min 5)"),
   Array("rol", "rol_description", "input", 22, "cumple tamaño maximo rol_description en ADD", "max_size", "ADD", "rol_description_max_size_ko", "Descripción muy larga (max 200)"),
   Array("rol", "rol_description", "input", 23, "cumple tamaño maximo rol_description en EDIT", "max_size", "EDIT", "rol_description_max_size_ko", "Descripción muy larga (max 200)"),
   Array("rol", "rol_description", "input", 24, "cumple tamaño maximo rol_description en SEARCH", "max_size", "SEARCH", "rol_description_max_size_ko", "Descripción muy larga (max 200)"),
   Array("rol", "rol_description", "input", 25, "cumple formato alfabetico con ñ, espacio y puntuacion en ADD", "format", "ADD", "rol_description_format_ko", "Formato inválido"),
   Array("rol", "rol_description", "input", 26, "cumple formato alfabetico con ñ, espacio y puntuacion en EDIT", "format", "EDIT", "rol_description_format_ko", "Formato inválido"),
   Array("rol", "rol_description", "input", 27, "cumple formato alfabetico con ñ, espacio y puntuacion en SEARCH", "format", "SEARCH", "rol_description_format_ko", "Formato inválido"),
   Array("rol", "rol_description", "input", 28, "es correcto rol_description en ADD", "valid", "ADD", true, "Descripción correcta"),
   Array("rol", "rol_description", "input", 29, "es correcto rol_description en EDIT", "valid", "EDIT", true, "Descripción correcta"),
   Array("rol", "rol_description", "input", 30, "es correcto rol_description en SEARCH", "valid", "SEARCH", true, "Descripción correcta")
);

let rol_pruebas = Array(
   Array("rol", "id_rol", 1, 1, "ADD", {"id_rol":0}, "id_rol_min_size_ko"),
   Array("rol", "id_rol", 1, 2, "ADD", {"id_rol":1}, true),
   Array("rol", "id_rol", 2, 3, "EDIT", {"id_rol":0}, "id_rol_min_size_ko"),
   Array("rol", "id_rol", 2, 4, "EDIT", {"id_rol":1}, true),
   Array("rol", "id_rol", 3, 5, "ADD", {"id_rol":12}, "id_rol_max_size_ko"),
   Array("rol", "id_rol", 3, 6, "ADD", {"id_rol":10}, true),
   Array("rol", "id_rol", 4, 7, "EDIT", {"id_rol":12}, "id_rol_max_size_ko"),
   Array("rol", "id_rol", 4, 8, "EDIT", {"id_rol":10}, true),
   Array("rol", "id_rol", 5, 9, "SEARCH", {"id_rol":12}, "id_rol_max_size_ko"),
   Array("rol", "id_rol", 5, 10, "SEARCH", {"id_rol":10}, true),
   Array("rol", "id_rol", 6, 11, "ADD", {"id_rol":5}, true),
   Array("rol", "id_rol", 7, 12, "EDIT", {"id_rol":5}, true),
   Array("rol", "id_rol", 8, 13, "SEARCH", {"id_rol":5}, true),
   Array("rol", "rol_name", 9, 14, "ADD", {"rol_name":"rol"}, "rol_name_min_size_ko"),
   Array("rol", "rol_name", 9, 15, "ADD", {"rol_name":"Admin"}, true),
   Array("rol", "rol_name", 10, 16, "EDIT", {"rol_name":"rol"}, "rol_name_min_size_ko"),
   Array("rol", "rol_name", 10, 17, "EDIT", {"rol_name":"Admin"}, true),
   Array("rol", "rol_name", 11, 18, "ADD", {"rol_name":"rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"}, "rol_name_max_size_ko"),
   Array("rol", "rol_name", 11, 19, "ADD", {"rol_name":"Administrator"}, true),
   Array("rol", "rol_name", 12, 20, "EDIT", {"rol_name":"rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"}, "rol_name_max_size_ko"),
   Array("rol", "rol_name", 12, 21, "EDIT", {"rol_name":"Administrator"}, true),
   Array("rol", "rol_name", 13, 22, "SEARCH", {"rol_name":"rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"}, "rol_name_max_size_ko"),
   Array("rol", "rol_name", 13, 23, "SEARCH", {"rol_name":"Administrator"}, true),
   Array("rol", "rol_name", 14, 24, "ADD", {"rol_name":"Admin123"}, "rol_name_format_ko"),
   Array("rol", "rol_name", 14, 25, "ADD", {"rol_name":"Manager"}, true),
   Array("rol", "rol_name", 15, 26, "EDIT", {"rol_name":"Admin123"}, "rol_name_format_ko"),
   Array("rol", "rol_name", 15, 27, "EDIT", {"rol_name":"Manager"}, true),
   Array("rol", "rol_name", 16, 28, "SEARCH", {"rol_name":"Admin123"}, "rol_name_format_ko"),
   Array("rol", "rol_name", 16, 29, "SEARCH", {"rol_name":"Manager"}, true),
   Array("rol", "rol_name", 17, 30, "ADD", {"rol_name":"Supervisor"}, true),
   Array("rol", "rol_name", 18, 31, "EDIT", {"rol_name":"Supervisor"}, true),
   Array("rol", "rol_name", 19, 32, "SEARCH", {"rol_name":"Supervisor"}, true),
   Array("rol", "rol_description", 20, 33, "ADD", {"rol_description":"desc"}, "rol_description_min_size_ko"),
   Array("rol", "rol_description", 20, 34, "ADD", {"rol_description":"Rol de administración"}, true),
   Array("rol", "rol_description", 21, 35, "EDIT", {"rol_description":"desc"}, "rol_description_min_size_ko"),
   Array("rol", "rol_description", 21, 36, "EDIT", {"rol_description":"Rol de administración"}, true),
   Array("rol", "rol_description", 22, 37, "ADD", {"rol_description":"ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd"}, "rol_description_max_size_ko"),
   Array("rol", "rol_description", 22, 38, "ADD", {"rol_description":"Acceso total a la gestión del sistema."}, true),
   Array("rol", "rol_description", 23, 39, "EDIT", {"rol_description":"ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd"}, "rol_description_max_size_ko"),
   Array("rol", "rol_description", 23, 40, "EDIT", {"rol_description":"Acceso total a la gestión del sistema."}, true),
   Array("rol", "rol_description", 24, 41, "SEARCH", {"rol_description":"ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd"}, "rol_description_max_size_ko"),
   Array("rol", "rol_description", 24, 42, "SEARCH", {"rol_description":"Acceso total a la gestión del sistema."}, true),
   Array("rol", "rol_description", 25, 43, "ADD", {"rol_description":"Rol_123_invalid"}, "rol_description_format_ko"),
   Array("rol", "rol_description", 25, 44, "ADD", {"rol_description":"Gestión de usuarios y contraseñas."}, true),
   Array("rol", "rol_description", 26, 45, "EDIT", {"rol_description":"Rol_123_invalid"}, "rol_description_format_ko"),
   Array("rol", "rol_description", 26, 46, "EDIT", {"rol_description":"Gestión de usuarios y contraseñas."}, true),
   Array("rol", "rol_description", 27, 47, "SEARCH", {"rol_description":"Rol_123_invalid"}, "rol_description_format_ko"),
   Array("rol", "rol_description", 27, 48, "SEARCH", {"rol_description":"Gestión de usuarios y contraseñas."}, true),
   Array("rol", "rol_description", 28, 49, "ADD", {"rol_description":"Permisos de edición y consulta."}, true),
   Array("rol", "rol_description", 29, 50, "EDIT", {"rol_description":"Permisos de edición y consulta."}, true),
   Array("rol", "rol_description", 30, 51, "SEARCH", {"rol_description":"Permisos de edición y consulta."}, true)
);
