let usuario_def_tests = Array(
   Array("usuario", "usuario", "input", 1, "cumple tamaño minimo usuario en ADD", "min_size", "ADD", "usuario_min_size_ko", "Usuario muy corto (min 5)"),
   Array("usuario", "usuario", "input", 2, "cumple tamaño minimo usuario en EDIT", "min_size", "EDIT", "usuario_min_size_ko", "Usuario muy corto (min 5)"),
   Array("usuario", "usuario", "input", 3, "cumple tamaño maximo usuario en ADD", "max_size", "ADD", "usuario_max_size_ko", "Usuario muy largo (max 45)"),
   Array("usuario", "usuario", "input", 4, "cumple tamaño maximo usuario en EDIT", "max_size", "EDIT", "usuario_max_size_ko", "Usuario muy largo (max 45)"),
   Array("usuario", "usuario", "input", 5, "cumple tamaño maximo usuario en SEARCH", "max_size", "SEARCH", "usuario_max_size_ko", "Usuario muy largo (max 45)"),
   Array("usuario", "usuario", "input", 6, "cumple formato usuario sin ñ ni acentos en ADD", "format", "ADD", "usuario_format_ko", "Formato inválido (solo caracteres alfabéticos sin ñ ni acentos)"),
   Array("usuario", "usuario", "input", 7, "cumple formato usuario sin ñ ni acentos en EDIT", "format", "EDIT", "usuario_format_ko", "Formato inválido (solo caracteres alfabéticos sin ñ ni acentos)"),
   Array("usuario", "usuario", "input", 8, "cumple formato usuario sin ñ ni acentos en SEARCH", "format", "SEARCH", "usuario_format_ko", "Formato inválido (solo caracteres alfabéticos sin ñ ni acentos)"),
   Array("usuario", "usuario", "input", 9, "es correcto usuario en ADD", "valid", "ADD", true, "Usuario correcto"),
   Array("usuario", "usuario", "input", 10, "es correcto usuario en EDIT", "valid", "EDIT", true, "Usuario correcto"),
   Array("usuario", "usuario", "input", 11, "es correcto usuario en SEARCH", "valid", "SEARCH", true, "Usuario correcto"),
   Array("usuario", "contrasena", "input", 12, "cumple tamaño minimo contrasena en ADD", "min_size", "ADD", "contrasena_min_size_ko", "Contraseña muy corta (min 8)"),
   Array("usuario", "contrasena", "input", 13, "cumple tamaño minimo contrasena en EDIT", "min_size", "EDIT", "contrasena_min_size_ko", "Contraseña muy corta (min 8)"),
   Array("usuario", "contrasena", "input", 14, "cumple tamaño maximo contrasena en ADD", "max_size", "ADD", "contrasena_max_size_ko", "Contraseña muy larga (max 45)"),
   Array("usuario", "contrasena", "input", 15, "cumple tamaño maximo contrasena en EDIT", "max_size", "EDIT", "contrasena_max_size_ko", "Contraseña muy larga (max 45)"),
   Array("usuario", "contrasena", "input", 16, "cumple formato contrasena sin ñ ni acentos en ADD", "format", "ADD", "contrasena_format_ko", "Formato inválido (sin ñ ni acentos)"),
   Array("usuario", "contrasena", "input", 17, "cumple formato contrasena sin ñ ni acentos en EDIT", "format", "EDIT", "contrasena_format_ko", "Formato inválido (sin ñ ni acentos)"),
   Array("usuario", "contrasena", "input", 18, "es correcto contrasena en ADD", "valid", "ADD", true, "Contraseña correcta"),
   Array("usuario", "contrasena", "input", 19, "es correcto contrasena en EDIT", "valid", "EDIT", true, "Contraseña correcta")
);

let usuario_pruebas = Array(
   Array("usuario", "usuario", 1, 1, "ADD", {"usuario":"user"}, "usuario_min_size_ko"),
   Array("usuario", "usuario", 1, 2, "ADD", {"usuario":"adminuser"}, true),
   Array("usuario", "usuario", 2, 3, "EDIT", {"usuario":"user"}, "usuario_min_size_ko"),
   Array("usuario", "usuario", 2, 4, "EDIT", {"usuario":"adminuser"}, true),
   Array("usuario", "usuario", 3, 5, "ADD", {"usuario":"uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu"}, "usuario_max_size_ko"),
   Array("usuario", "usuario", 3, 6, "ADD", {"usuario":"adminuser"}, true),
   Array("usuario", "usuario", 4, 7, "EDIT", {"usuario":"uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu"}, "usuario_max_size_ko"),
   Array("usuario", "usuario", 4, 8, "EDIT", {"usuario":"adminuser"}, true),
   Array("usuario", "usuario", 5, 9, "SEARCH", {"usuario":"uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu"}, "usuario_max_size_ko"),
   Array("usuario", "usuario", 5, 10, "SEARCH", {"usuario":"adminuser"}, true),
   Array("usuario", "usuario", 6, 11, "ADD", {"usuario":"niño_user"}, "usuario_format_ko"),
   Array("usuario", "usuario", 6, 12, "ADD", {"usuario":"adminuser"}, true),
   Array("usuario", "usuario", 7, 13, "EDIT", {"usuario":"niño_user"}, "usuario_format_ko"),
   Array("usuario", "usuario", 7, 14, "EDIT", {"usuario":"adminuser"}, true),
   Array("usuario", "usuario", 8, 15, "SEARCH", {"usuario":"niño_user"}, "usuario_format_ko"),
   Array("usuario", "usuario", 8, 16, "SEARCH", {"usuario":"adminuser"}, true),
   Array("usuario", "usuario", 9, 17, "ADD", {"usuario":"johndoe"}, true),
   Array("usuario", "usuario", 10, 18, "EDIT", {"usuario":"johndoe"}, true),
   Array("usuario", "usuario", 11, 19, "SEARCH", {"usuario":"johndoe"}, true),
   Array("usuario", "contrasena", 12, 20, "ADD", {"contrasena":"pass"}, "contrasena_min_size_ko"),
   Array("usuario", "contrasena", 12, 21, "ADD", {"contrasena":"password123"}, true),
   Array("usuario", "contrasena", 13, 22, "EDIT", {"contrasena":"pass"}, "contrasena_min_size_ko"),
   Array("usuario", "contrasena", 13, 23, "EDIT", {"contrasena":"password123"}, true),
   Array("usuario", "contrasena", 14, 24, "ADD", {"contrasena":"pppppppppppppppppppppppppppppppppppppppppppppp"}, "contrasena_max_size_ko"),
   Array("usuario", "contrasena", 14, 25, "ADD", {"contrasena":"password123"}, true),
   Array("usuario", "contrasena", 15, 26, "EDIT", {"contrasena":"pppppppppppppppppppppppppppppppppppppppppppppp"}, "contrasena_max_size_ko"),
   Array("usuario", "contrasena", 15, 27, "EDIT", {"contrasena":"password123"}, true),
   Array("usuario", "contrasena", 16, 28, "ADD", {"contrasena":"contraseña12"}, "contrasena_format_ko"),
   Array("usuario", "contrasena", 16, 29, "ADD", {"contrasena":"secretPass123"}, true),
   Array("usuario", "contrasena", 17, 30, "EDIT", {"contrasena":"contraseña12"}, "contrasena_format_ko"),
   Array("usuario", "contrasena", 17, 31, "EDIT", {"contrasena":"secretPass123"}, true),
   Array("usuario", "contrasena", 18, 32, "ADD", {"contrasena":"securePass2026"}, true),
   Array("usuario", "contrasena", 19, 33, "EDIT", {"contrasena":"securePass2026"}, true)
);
